[platformio]
src_dir = main
default_envs = esp32c6

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf

monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 4MB
board_build.partitions = partitions.csv

build_flags =
    -D CONFIG_ZB_ENABLED=1
    -D CONFIG_ZB_COORDINATOR_ROLE=1

monitor_filters = esp32_exception_decoder