[platformio]
src_dir = main

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf
monitor_speed = 115200

board_upload.flash_size = 4MB

board_build.partitions = partitions.csv

build_flags = -D CONFIG_LWIP_IPV4=1
              -D CONFIG_ZB_ENABLED=1
              -D CONFIG_ZB_COORDINATOR_ROLE=1
